FROM centos
MAINTAINER paddyace <huangblcs@outlook.com> 

RUN yum update -y && yum install -y git vim python3
RUN git clone https://github.com/chxuan/vimplus.git ~/.vimplus && cd ~/.vimplus && ./install.sh

EXPOSE  22

CMD /usr/sbin/sshd -D
