FROM centos
MAINTAINER paddyace <huangblcs@outlook.com> 

RUN yum update -y && yum groupinstall -y "Development Tools" 
RUN yum install -y epel-release cmake vim boost boost-devel

EXPOSE  22

CMD /usr/sbin/sshd -D

