FROM ubuntu
MAINTAINER paddyace <huangblcs@outlook.com> 

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install -y tzdata \
    && ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && dpkg-reconfigure --frontend noninteractive tzdata

RUN apt update -y && apt install -y gcc g++ git make cmake vim
RUN apt install -y libboost-all-dev libicu-dev libgtest-dev

EXPOSE  22

CMD /usr/sbin/sshd -D

