FROM ubuntu
MAINTAINER paddyace <huangblcs@outlook.com> 

RUN apt update -y && apt install -y gcc g++ git make cmake vim
RUN apt install -y libboost-all-dev libicu-dev libgtest-dev

EXPOSE  22

CMD /usr/sbin/sshd -D

